spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate



# logback 설정 경로
logging:
  config: classpath:logback/logback-prod.xml